Repository TEAM3x3/backend, pull requests merged in 2020-08, with the labels that each got.

#23 crawling
  .idea/.gitignore
  .idea/13-final-maketkurly.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app/config/__init__.py
  app/config/asgi.py
  app/config/settings.py
  app/config/urls.py
  app/config/wsgi.py
  app/goods/__init__.py
  app/goods/admin.py
  app/goods/apps.py
  app/goods/migrations/__init__.py
  app/goods/models.py
  app/goods/tests.py
  app/goods/views.py
  app/manage.py
  app/members/__init__.py
  app/members/admin.py
  app/members/apps.py
  app/members/migrations/0001_initial.py
  app/members/migrations/__init__.py
  app/members/models.py
  app/members/tests.py
  app/members/views.py
  readme.md
  크롤링.ipynb
Labels: enhancement

#24 crawling#1
  .idea/dataSources.xml
  app/config/settings.py
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/migrations/0001_initial.py
  app/goods/models.py
  development_journal.md
  readme.md
  크롤링.ipynb
Labels: enhancement

#25 Feature/crawling
  .idea/dataSources.xml
  app/config/settings.py
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/migrations/0001_initial.py
  app/goods/models.py
  development_journal.md
  readme.md
  크롤링.ipynb
Labels: enhancement

#28 feature/user
  .idea/13-final-maketkurly.iml
  .idea/dataSources.xml
  app/core/urls.py
  app/goods/migrations/0001_initial.py
  app/members/migrations/0001_initial.py
  app/members/migrations/0002_remove_user_password_check.py
  app/members/models.py
  app/members/serializers.py
  app/members/test.py
Labels: enhancement

#29 Feature/user
  .idea/13-final-maketkurly.iml
  .idea/dataSources.xml
  app/core/urls.py
  app/goods/migrations/0001_initial.py
  app/members/migrations/0001_initial.py
  app/members/migrations/0002_remove_user_password_check.py
  app/members/models.py
  app/members/serializers.py
  app/members/test.py
Labels: enhancement

#30 feature/code
  .gitignore
  .idea/.gitignore
  .idea/13-final-maketkurly.iml
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  app/.idea/.gitignore
  app/.idea/app.iml
  app/.idea/inspectionProfiles/Project_Default.xml
  app/.idea/inspectionProfiles/profiles_settings.xml
  app/.idea/misc.xml
  app/.idea/modules.xml
  app/.idea/vcs.xml
  app/.idea/workspace.xml
  app/config/settings.py
  app/config/urls.py
  app/datadump.json
  app/goods/crawling.py
  app/goods/migrations/0001_initial.py
  app/goods/models.py
  app/goods/views.py
  app/members/admin.py
  app/members/migrations/0001_initial.py
  app/members/models.py
  app/members/serializers.py
  development_journal.md
  requirements-pro.txt
  requirements.txt
  크롤링.ipynb
Labels: enhancement

#34 Develop
  .gitignore
  app/config/settings/base.py
  app/core/urls.py
  app/datadump.json
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/views.py
  app/members/migrations/0001_initial.py
  app/members/serializers.py
  app/크롤링.ipynb
  development_journal.md
Labels: enhancement

#35 Develop
  app/cart/__init__.py
  app/cart/admin.py
  app/cart/apps.py
  app/cart/migrations/0001_initial.py
  app/cart/migrations/__init__.py
  app/cart/models.py
  app/cart/serializers.py
  app/cart/tests.py
  app/cart/views.py
  app/config/settings/base.py
  app/config/settings/dev.py
  app/core/urls.py
  app/goods/migrations/0001_initial.py
  app/goods/migrations/0002_auto_20200821_1936.py
  app/goods/migrations/0003_auto_20200822_1433.py
  app/goods/migrations/0004_auto_20200822_1453.py
  app/goods/serializers.py
  app/members/migrations/0001_initial.py
Labels: enhancement

#36 Develop
  app/carts/__init__.py
  app/carts/admin.py
  app/carts/apps.py
  app/carts/migrations/0001_initial.py
  app/carts/migrations/0002_cartitem_user.py
  app/carts/migrations/__init__.py
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/config/settings/base.py
  app/config/settings/dev.py
  app/config/settings/productions.py
  app/core/urls.py
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/models.py
  app/goods/views.py
  app/members/admin.py
  app/members/models.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
  docker/docker-compose.yml
Labels: enhancement

#37 Develop
  app/carts/admin.py
  readme.md
Labels: enhancement

#40 Develop
  app/cart/__init__.py
  app/cart/admin.py
  app/cart/apps.py
  app/cart/migrations/0001_initial.py
  app/cart/migrations/__init__.py
  app/cart/models.py
  app/cart/serializers.py
  app/cart/tests.py
  app/cart/views.py
  app/carts/admin.py
  app/carts/migrations/0001_initial.py
  app/carts/migrations/0002_cartitem_user.py
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/config/settings/base.py
  app/config/settings/dev.py
  app/core/urls.py
  app/datadump.json
  app/goods/crawling.py
  app/goods/models.py
  app/goods/tests.py
  app/goods/views.py
  app/members/models.py
  app/크롤링.ipynb
  development_journal.md
Labels: enhancement

#41 Develop
  .gitignore
  readme.md
  requirements.txt
Labels: enhancement

#43 Develop
  .gitignore
  app/carts/admin.py
  app/carts/migrations/0001_initial.py
  app/carts/migrations/0002_cartitem_user.py
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/config/settings/base.py
  app/core/urls.py
  app/goods/filters.py
  app/goods/views.py
  app/members/views.py
  develop_log.md
Labels: enhancement, refactoring, test

#44 Develop
  .gitignore
  app/cart/migrations/__init__.py
  app/carts/admin.py
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/config/settings/base.py
  app/config/settings/dev.py
  app/config/settings/productions.py
  app/core/urls.py
  app/datadump.json
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/filters.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/tests.py
  app/goods/views.py
  app/members/models.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
  app/크롤링.ipynb
  develop_log.md
  readme.md
  requirements.txt
Labels: enhancement, refactoring

#45 Feature/cart
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/core/urls.py
  app/goods/admin.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/tests.py
  app/members/models.py
  requirements.txt
Labels: enhancement, refactoring

#46 refactor: confilct solve
  app/config/asgi.py
  app/config/wsgi.py
  app/goods/admin.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/views.py
  app/manage.py
Labels: refactoring
