Repository TEAM3x3/backend, pull requests merged in 2020-09, with the labels that each got.

#51 feature: cart retrieve pk permission
  app/carts/permissions.py
  app/carts/views.py
  app/config/asgi.py
  app/config/wsgi.py
  app/goods/admin.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/views.py
  app/manage.py
  readme.md
Labels: enhancement

#52 Feature/cart
  app/carts/permissions.py
  app/carts/views.py
Labels: enhancement

#53 Feature/crawling
  .gitignore
  app/cart/migrations/__init__.py
  app/carts/admin.py
  app/carts/migrations/0001_initial.py
  app/carts/migrations/0002_cartitem_user.py
  app/carts/models.py
  app/carts/permissions.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/config/asgi.py
  app/config/settings/base.py
  app/config/settings/dev.py
  app/config/settings/productions.py
  app/config/wsgi.py
  app/core/urls.py
  app/datadump.json
  app/goods/admin.py
  app/goods/crawling.py
  app/goods/filters.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/tests.py
  app/goods/views.py
  app/manage.py
  app/members/models.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
  app/크롤링.ipynb
  develop_log.md
  readme.md
  requirements.txt
Labels: enhancement

#54 Develop
  app/event/__init__.py
  app/event/admin.py
  app/event/apps.py
  app/event/models.py
  app/event/serializers.py
  app/event/tests.py
  app/event/views.py
  app/goods/crawling/__init__.py
  app/goods/crawling/event.py
  app/goods/crawling/goods.py
Labels: enhancement

#55 Feature/crawling & event
  app/event/__init__.py
  app/event/admin.py
  app/event/apps.py
  app/event/models.py
  app/event/serializers.py
  app/event/tests.py
  app/event/views.py
  app/goods/crawling/__init__.py
  app/goods/crawling/event.py
  app/goods/crawling/goods.py
Labels: enhancement

#56 refactor: event view, model
  app/config/asgi.py
  app/config/settings/base.py
  app/config/wsgi.py
  app/core/urls.py
  app/datadump.json
  app/event/models.py
  app/event/serializers.py
  app/goods/crawling/event.py
  app/goods/models.py
  app/manage.py
Labels: enhancement

#58 Test/cart
  app/carts/admin.py
  app/carts/tests.py
  app/core/urls.py
  app/datadump.json
  app/goods/serializers.py
  app/members/tests.py
Labels: enhancement

#59 refactor: cart testcode 완성
  app/carts/permissions.py
  app/carts/tests.py
  app/carts/views.py
  app/datadump.json
  app/goods/serializers.py
Labels: enhancement, test

#64 refactor: productions.py
  app/config/settings/productions.py
  app/datadump.json
Labels: enhancement

#67 HomePage-'이 상품 어때요 구현
  app/goods/serializers.py
  app/goods/views.py
Labels: enhancement

#68 Feature/order
  app/carts/models.py
  app/config/settings/base.py
  app/core/urls.py
  app/datadump.json
  app/goods/views.py
  app/members/models.py
  app/members/serializers.py
  app/order/__init__.py
  app/order/admin.py
  app/order/apps.py
  app/order/models.py
  app/order/serializers.py
  app/order/tests.py
  app/order/views.py
Labels: enhancement

#69 Feature/order
  app/carts/models.py
  app/carts/serializers.py
  app/core/urls.py
  app/event/models.py
  app/goods/admin.py
  app/goods/models.py
  app/goods/serializers.py
  app/members/admin.py
  app/members/serializers.py
  app/members/views.py
  app/order/models.py
  app/order/serializers.py
  app/order/views.py
  develop_log.md
Labels: enhancement

#75 refactor: issue#70, goods testcode
  app/config/settings/dev.py
  app/config/settings/dev_test.py
  app/goods/models.py
  app/goods/tests.py
Labels: enhancement

#76 Refactor/order 유저 기본 배송지 설정, bulk update, 면역력 증진
  app/carts/permissions.py
  app/carts/tests.py
  app/core/urls.py
  app/goods/serializers.py
  app/goods/views.py
  app/members/admin.py
  app/members/models.py
  app/members/serializers.py
  app/members/views.py
  app/order/models.py
Labels: enhancement

#77 refactor: goods higher lock key 에 의한 카테고리별 상품 필터링 코드 수정
  app/goods/views.py
Labels: enhancement

#78 Test/goods
  app/carts/models.py
  app/config/settings/base.py
  app/core/urls.py
  app/datadump.json
  app/goods/models.py
  app/goods/tests.py
  app/goods/views.py
  app/members/serializers.py
  app/members/views.py
  app/order/models.py
  app/order/serializers.py
  develop_log.md
Labels: enhancement, invalid, question, refactoring, test

#80 feature: kurlys 추천 홈 - 컬리추천 최 상단 이벤트 페이지
  app/Untitled.ipynb
  app/core/urls.py
  app/event/admin.py
  app/event/models.py
  app/event/serializers.py
  app/event/views.py
  app/goods/crawling/goods.py
  app/goods/crawling/mainevent.py
Labels: enhancement

#82 Feature/goods
  app/goods/models.py
  app/goods/serializers.py
Labels: enhancement

#86 feature : total quantity of goods in cart / F expression, transaction
  app/carts/models.py
  app/carts/serializers.py
  app/event/serializers.py
  develop_log.md
Labels: enhancement, question

#87 feature : total quantity of goods in cart when delete
  app/carts/models.py
Labels: enhancement

#92 Feature/search
  app/core/urls.py
  app/goods/views.py
  app/members/admin.py
  app/members/models.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
Labels: enhancement

#91 Feature/user
  app/carts/permissions.py
  app/config/settings/base.py
  app/goods/filters.py
  app/goods/tests.py
  app/goods/views.py
  app/members/permissions.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
Labels: enhancement

#96 refactor: sales price, sales discount rate for goods detail
  app/goods/models.py
  app/goods/serializers.py
Labels: enhancement

#98 Feature/user
  app/core/urls.py
  app/goods/tests.py
  app/members/models.py
  app/members/permissions.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
Labels: enhancement

#102 Feature/cart
  app/carts/models.py
  app/carts/serializers.py
  app/carts/tests.py
  app/carts/views.py
  app/core/urls.py
  app/goods/models.py
  app/goods/serializers.py
  app/goods/tests.py
  app/goods/views.py
  app/members/tests.py
Labels: enhancement

#103 goods 상품명검색, cart 선택삭제 구현
  app/carts/views.py
  app/goods/views.py
Labels: enhancement

#104 refactor: serializer field 데이터 추가 및 마켓컬리 이미지 str로 받는 경우 이벤트 내려가게 되면 사…
  app/carts/serializers.py
  app/event/models.py
  app/event/serializers.py
Labels: refactoring

#108 최근 검색어 / 인기 검색어 구현
  app/members/views.py
Labels: enhancement

#110 feature: review & Refactor TS-2
  app/core/urls.py
  app/members/views.py
  app/order/serializers.py
  app/order/views.py
Labels: enhancement, refactoring

#112 최근검색어/ 인기검색어
  app/members/models.py
  app/members/serializers.py
  app/members/views.py
Labels: enhancement

#113 최근검색어/ 인기검색어3
  app/goods/tests.py
  app/goods/views.py
  app/members/serializers.py
  app/members/tests.py
  app/members/views.py
Labels: enhancement

#114 feature: goods review
  app/goods/views.py
  app/members/views.py
Labels: enhancement

#115 Refactor/order 주문서 모델 리팩토링
  app/carts/permissions.py
  app/carts/tests.py
  app/carts/views.py
  app/goods/tests.py
  app/members/permissions.py
  app/members/serializers.py
  app/members/views.py
  app/order/models.py
Labels: enhancement

#117 category image file upload2
  app/goods/models.py
Labels: enhancement

#118 상품명 검색, 이 상품 어때요 테스트코드
  app/config/settings/test.py
  app/goods/models.py
  app/goods/tests.py
  app/goods/views.py
Labels: enhancement

#121 refactor: category serializers fields
  app/goods/serializers.py
Labels: refactoring

#124 Feature/payment
  app/core/views.py
  app/goods/serializers.py
  app/members/models.py
  app/order/tests.py
  app/order/views.py
  develop_log.md
Labels: documentation, enhancement, question

#125 feature: goods sales 할인 상품들의 샛별배송, 택배배송, 할인률에 따른 필터링
  app/goods/admin.py
  app/goods/views.py
Labels: enhancement

#126 Feature/payment 결제시 주문 상태,결제 정보 추가
  app/config/settings/base.py
  app/members/admin.py
  app/members/models.py
  app/order/models.py
  app/order/serializers.py
  app/order/signals.py
  app/order/tests.py
  app/order/views.py
Labels: enhancement

#127 feature: goods filtering & ordering
  app/config/settings/base.py
  app/event/filters.py
  app/event/serializers.py
  app/event/views.py
  app/goods/filters.py
  app/goods/views.py
  develop_log.md
Labels: enhancement

#129 refactor: api/goods/sales, issue
  app/goods/views.py
Labels: invalid, question, refactoring

#130 Develop
  app/carts/tests.py
  app/goods/serializers.py
  app/goods/views.py
  app/members/models.py
  app/members/serializers.py
  app/order/views.py
Labels: enhancement

#133 refactor : api- docs #goods, order, review 해야 함
  app/carts/serializers.py
  app/carts/views.py
  app/core/instructors.py
  app/core/urls.py
  app/event/serializers.py
  app/event/views.py
  app/goods/serializers.py
  app/goods/views.py
  app/members/models.py
  app/members/serializers.py
  app/members/views.py
  app/order/views.py
Labels: documentation, enhancement, refactoring

#134 refactor : filtering data docs
  app/event/serializers.py
  app/event/views.py
  app/goods/serializers.py
Labels: documentation, enhancement
